---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-test
  namespace: github-actions-test
spec:
    spec:
      containers:
        - name: Hello World
          image: hello-world
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
