on: push
jobs:
  test_wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1.2.0
        with:
          endpoint: ${{ secrets.WG_ENDPOINT }}
          endpoint_public_key: ${{ secrets.WG_ENDPOINT_PUBKEY }}
          ips: 192.168.253.10/24
          allowed_ips: 192.168.253.0/24, 10.4.0.0/24
          private_key: ${{ secrets.WG_CLIENT_PRIVKEY }}

      - name: "Create Namespace"
        uses: neosec-com/kubectl-aws-eks@1.1.2
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: kubectl create namespace hello-world

      - name: "Create configmap"
        uses: neosec-com/kubectl-aws-eks@1.1.2
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: kubectl -n hello-world create configmap hello-world --from-file k3s/hello-world/index.html

      - name: "Deployment"
        uses: neosec-com/kubectl-aws-eks@1.1.2
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: kubectl -n hello-world apply -f k3s/hello-world/deployment.yml
