on: push
jobs:
  test_wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1.2.0
        with:
          endpoint: '${{ secrets.WG_ENDPOINT }}'
          endpoint_public_key: '${{ secrets.WG_ENDPOINT_PUBLICKEY }}'
          ips: 172.16.16.100/24
          allowed_ips: 10.4.0.0/24
          private_key: '${{ secrets.WG_CLIENT_PRIVKEY }}'
      - name: "Test K3s API"
        uses: sozo-design/curl@v1.0.2
        with:
          args: --insecure https://10.4.0.23:6443
